[package]
name = "bevy_my_character"
version = "0.1.0"
edition = "2021"

[dependencies]
avian3d = "0.2.1"
bevy = "0.15.2"
bevy-tnua = "0.21.0"
bevy-tnua-avian3d = "0.2.0"
bevy_egui = "0.32.0"
rand = "0.9.0"
